/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vn_ntv_jword_segment_Predictor */

#ifndef _Included_org_vn_ntv_jword_segment_Predictor
#define _Included_org_vn_ntv_jword_segment_Predictor
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_vn_ntv_jword_segment_Predictor
 * Method:    createNativeObject
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_vn_ntv_jword_segment_Predictor_createNativeObject
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_vn_ntv_jword_segment_Predictor
 * Method:    deleteNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_vn_ntv_jword_segment_Predictor_deleteNativeObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_vn_ntv_jword_segment_Predictor
 * Method:    printObjectDetails
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_vn_ntv_jword_segment_Predictor_printObjectDetails
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_vn_ntv_jword_segment_Predictor
 * Method:    segment
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_vn_ntv_jword_segment_Predictor_segment
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_vn_ntv_jword_segment_Predictor
 * Method:    execute
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_vn_ntv_jword_segment_Predictor_execute
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
